/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ShikeApplication_ndkdemo_ndktool */

#ifndef _Included_com_example_ShikeApplication_ndkdemo_ndktool
#define _Included_com_example_ShikeApplication_ndkdemo_ndktool
#endif
