/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ShikeApplication_ndkdemo_ndktool */

#ifndef _Included_com_example_ShikeApplication_ndkdemo_ndktool
#define _Included_com_example_ShikeApplication_ndkdemo_ndktool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ShikeApplication_ndkdemo_ndktool
 * Method:    getSomeDumpTextFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ShikeApplication_ndkdemo_ndktool_getSomeDumpTextFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
